services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
    php:
        container_name: php-fpm
        hostname: php
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/html
        networks:
            - default
    mysql:
        container_name: mysql
        hostname: mysql
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=parser_db
            - MYSQL_USER=parser_db
            - MYSQL_PASSWORD=shit
        volumes:
            - './docker/mysql:/var/lib/mysql'
